name: storeImageGenerator
version: 0.0.2
description: A script to generate app store / play store images
author: Markus Krebs <markuskrebs93@gmail.com>
environment: 
  sdk: '>=2.9.0 <3.0.0'
# dependencies
dependencies: 
  args: ^1.6.0
  dcli: ^0.39.4
  path: ^1.7.0
  image: ^2.1.19
# dev dependencies
dev_dependencies: 
  pedantic: ^1.9.2

# dart scripts
executables:
  # start local http dart_backend server
  storeImageGen: storeImageGenerator
