name: storeImageGenerator
version: 0.0.3
description: A script to generate app store / play store images
author: Markus Krebs <markuskrebs93@gmail.com>
environment: 
  sdk: '>=2.12.0'
# dependencies
dependencies: 
  args: ^2.3.0
  dcli: ^1.30.2
  path: ^1.8.1
  image: ^3.1.3
# dev dependencies
dev_dependencies: 
  pedantic: ^1.11.1
  test: any

# dart scripts
executables:
  # start local http dart_backend server
  storeImageGen: storeImageGenerator
