name: storeImageGenerator
version: 0.1.0
description: A script to generate app store / play store images
environment:
  sdk: '>=2.12.0'
# dependencies
dependencies: 
  dcli: ^1.30.2
  image: ^3.1.3
# dev dependencies
dev_dependencies: 
  pedantic: ^1.11.1
  test: any

# dart scripts
executables:
  storeImageGen: storeImageGenerator
