name: storeImageGenerator
version: 0.0.2
description: A script to generate app store / play store images
author: Markus Krebs <markuskrebs93@gmail.com>
environment: 
  sdk: '>=2.12.0'
# dependencies
dependencies: 
  args: ^2.0.0
  dcli: ^0.50.2
  path: ^1.8.0
  image: ^3.0.1
# dev dependencies
dev_dependencies: 
  pedantic: ^1.11.0

# dart scripts
executables:
  # start local http dart_backend server
  storeImageGen: storeImageGenerator
